# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-04 14:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='login',
            old_name='team',
            new_name='nickname',
        ),
    ]
