# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-04 14:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Activity', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ucsmaddacivity',
            old_name='Fidetails',
            new_name='fiDetails',
        ),
        migrations.AddField(
            model_name='ucsmaddacivity',
            name='engineer',
            field=models.CharField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
    ]
