# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-04 04:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Activity', '0002_auto_20170604_2022'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestBedSetup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=20)),
                ('cimc_ip', models.CharField(max_length=50)),
                ('server_type', models.CharField(max_length=200)),
                ('cimc_bios', models.CharField(max_length=50)),
                ('firmware_upgrade_prs', models.CharField(max_length=250)),
            ],
        ),
    ]
