# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-04 04:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Activity', '0003_testbedsetup'),
    ]

    operations = [
        migrations.CreateModel(
            name='StandaloneTestBedSetup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=20)),
                ('cimc_ip', models.CharField(max_length=50)),
                ('server_type', models.CharField(max_length=50)),
                ('cimc_bios_version', models.CharField(max_length=50)),
                ('firmware_upgrade_prs', models.CharField(max_length=250)),
                ('adapter_name', models.CharField(max_length=20)),
                ('adapter_slot', models.CharField(max_length=10)),
                ('adapter_fw', models.CharField(max_length=50)),
                ('boot_type', models.CharField(max_length=10)),
                ('bios_bootcode', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UcsmTestBedSetup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fi_ip', models.CharField(max_length=50)),
                ('fi_firmware', models.CharField(max_length=50)),
                ('server_type', models.CharField(max_length=50)),
                ('server_number', models.CharField(max_length=10)),
                ('cimc_version', models.CharField(max_length=50)),
                ('cimc_bios_version', models.CharField(max_length=50)),
                ('discovery_methods', models.CharField(max_length=250)),
                ('adapter_name', models.CharField(max_length=20)),
                ('adapter_slot', models.CharField(max_length=10)),
                ('adapter_fw', models.CharField(max_length=50)),
                ('boot_type', models.CharField(max_length=10)),
                ('bios_bootcode', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='TestBedSetup',
        ),
    ]
