# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-18 14:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Activity', '0008_auto_20170718_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='testexecution',
            name='os',
            field=models.CharField(default='NA', max_length=50),
        ),
    ]
