# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-19 04:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Activity', '0009_testexecution_os'),
    ]

    operations = [
        migrations.CreateModel(
            name='StandaloneTestBedSetupFinal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engineer', models.CharField(max_length=10)),
                ('cimc_ip', models.CharField(max_length=50)),
                ('server_type', models.CharField(max_length=50)),
                ('cimc_bios_version', models.CharField(max_length=50)),
                ('firmware_upgrade_prs', models.CharField(max_length=250)),
                ('adapter_name', models.CharField(max_length=20)),
                ('adapter_slot', models.CharField(max_length=10)),
                ('adapter_fw', models.CharField(max_length=50)),
                ('target_type', models.CharField(max_length=10)),
                ('bios_bootcode', models.CharField(max_length=50)),
                ('effort', models.CharField(default='N', max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='testexecution',
            name='id',
        ),
        migrations.AddField(
            model_name='testexecution',
            name='testbed',
            field=models.CharField(default='NA', editable=False, max_length=500, primary_key=True, serialize=False),
        ),
    ]
