# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-19 05:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Activity', '0011_auto_20170719_1009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testexecution',
            name='testbed',
        ),
        migrations.AddField(
            model_name='testexecution',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testexecution',
            name='testbed_stand',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Activity.StandaloneTestBedSetup'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testexecution',
            name='testbed_ucsm',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Activity.UcsmTestBedSetup'),
            preserve_default=False,
        ),
    ]
