# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-19 07:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Activity', '0013_auto_20170719_1226'),
    ]

    operations = [
        migrations.CreateModel(
            name='UcsmTestBedSetupFinal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engineer', models.CharField(max_length=10)),
                ('fi_ip', models.CharField(max_length=50)),
                ('fi_firmware', models.CharField(max_length=50)),
                ('server_type', models.CharField(max_length=50)),
                ('server_number', models.CharField(max_length=10)),
                ('cimc_version', models.CharField(max_length=50)),
                ('cimc_bios_version', models.CharField(max_length=50)),
                ('discovery_methods', models.CharField(max_length=250)),
                ('adapter_name', models.CharField(max_length=20)),
                ('adapter_slot', models.CharField(max_length=10)),
                ('adapter_fw', models.CharField(max_length=50)),
                ('target_type', models.CharField(max_length=10)),
                ('bios_bootcode', models.CharField(max_length=50)),
                ('effort', models.CharField(default='N', max_length=10)),
            ],
        ),
    ]
