# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-24 11:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Activity', '0018_standalonetestbedsetupfinal_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='ucsmtestbedsetupfinal',
            name='event',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
