# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2010-07-07 13:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Activity', '0020_auto_20100630_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='testexecution',
            name='event',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
