# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-04 19:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Activity', '0022_auto_20170904_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standalonetestbedsetup',
            name='adapter_name',
            field=models.CharField(max_length=999),
        ),
        migrations.AlterField(
            model_name='standalonetestbedsetup',
            name='adapter_slot',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='standalonetestbedsetup',
            name='cimc_bios_version',
            field=models.CharField(max_length=90),
        ),
        migrations.AlterField(
            model_name='standalonetestbedsetup',
            name='target_type',
            field=models.CharField(max_length=99),
        ),
        migrations.AlterField(
            model_name='standalonetestbedsetupfinal',
            name='adapter_name',
            field=models.CharField(max_length=999),
        ),
        migrations.AlterField(
            model_name='standalonetestbedsetupfinal',
            name='adapter_slot',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='standalonetestbedsetupfinal',
            name='cimc_bios_version',
            field=models.CharField(max_length=90),
        ),
        migrations.AlterField(
            model_name='standalonetestbedsetupfinal',
            name='target_type',
            field=models.CharField(max_length=99),
        ),
        migrations.AlterField(
            model_name='ucsmtestbedsetupfinal',
            name='adapter_name',
            field=models.CharField(max_length=999),
        ),
        migrations.AlterField(
            model_name='ucsmtestbedsetupfinal',
            name='cimc_bios_version',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='ucsmtestbedsetupfinal',
            name='effort',
            field=models.CharField(blank=True, default='N', max_length=10),
        ),
        migrations.AlterField(
            model_name='ucsmtestbedsetupfinal',
            name='target_type',
            field=models.CharField(max_length=99),
        ),
    ]
