# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-28 05:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Activity', '0023_auto_20170904_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standalonetestbedsetup',
            name='release',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='standalonetestbedsetupfinal',
            name='release',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='ucsmtestbedsetup',
            name='release',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='ucsmtestbedsetupfinal',
            name='release',
            field=models.CharField(max_length=50),
        ),
    ]
